---
format_version: 2
pipelines:
  in-app-tool:
    group: marketing-tech-team
    label_template: "${COUNT}-${git[:7]}"
    materials:
      git:
        git: git@github.com:soundcloud/in-app-tool.git
    stages:
      - build:
          jobs:
            publish:
              tasks:
                - exec:
                    command: make
                    arguments:
                      - "-f"
                      - Makefile.pipeline
                      - build
                      - assemble
                      - package
                      - publish
      - promote:
          jobs:
            publish:
              tasks:
                - exec:
                    command: make
                    arguments:
                      - "-f"
                      - Makefile.pipeline
                      - promote-to-stable
                      - promote-to-release
      - deploy:
          jobs:
            deploy:
              job_type: deploy
              tasks:
                - exec:
                    command: make
                    arguments:
                      - "-f"
                      - Makefile.pipeline
                      - publish-deploy
                      - deploy
